# Generated by Django 4.2.29 on 2026-04-01 10:53

import apps.pdf.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.pdf.models.pdf_upload_path)),
                ('result', models.FileField(blank=True, null=True, upload_to=apps.pdf.models.pdf_processed_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tool', models.CharField(choices=[('compress', 'Compress'), ('merge', 'Merge'), ('split', 'Split')], default='compress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
