# Generated by Django 4.2.29 on 2026-04-01 14:30

import apps.pdf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='files',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='page_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.pdf.models.pdf_upload_path),
        ),
    ]
