# Generated by Django 4.2.29 on 2026-04-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_job_files_job_page_range_alter_job_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='compression_level',
            field=models.CharField(default='extreme', max_length=20),
        ),
    ]
