# Generated by Django 4.2.29 on 2026-04-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_job_compression_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('name_kh', models.CharField(max_length=200, verbose_name='Name (Khmer)')),
                ('day', models.IntegerField(verbose_name='Day')),
                ('month', models.IntegerField(verbose_name='Month')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public Holiday')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['month', 'day'],
            },
        ),
    ]
