# Generated by Django 4.2.29 on 2026-04-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_holiday_date_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_kh', models.CharField(max_length=200, verbose_name='Title (Khmer)')),
                ('description_en', models.TextField(blank=True)),
                ('description_kh', models.TextField(blank=True, verbose_name='Description (Khmer)')),
                ('event_type', models.CharField(choices=[('public', 'Public Holiday'), ('religious', 'Religious Day'), ('national', 'National Day'), ('festival', 'Festival'), ('custom', 'Custom Event')], default='custom', max_length=20)),
                ('solar_date', models.DateField(blank=True, null=True)),
                ('lunar_month', models.IntegerField(blank=True, null=True)),
                ('lunar_day', models.IntegerField(blank=True, null=True)),
                ('lunar_year', models.IntegerField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['solar_date', 'lunar_month', 'lunar_day'],
            },
        ),
        migrations.CreateModel(
            name='LunarDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_date', models.DateField(unique=True)),
                ('lunar_month', models.IntegerField()),
                ('lunar_day', models.IntegerField()),
                ('lunar_year', models.IntegerField()),
                ('khmer_month_name', models.CharField(max_length=50)),
                ('khmer_day_name', models.CharField(max_length=50)),
                ('is_holy_day', models.BooleanField(default=False)),
                ('is_full_moon', models.BooleanField(default=False)),
                ('is_new_moon', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lunar Date',
                'verbose_name_plural': 'Lunar Dates',
                'ordering': ['-solar_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='holiday',
            name='is_lunar',
            field=models.BooleanField(default=False, verbose_name='Lunar Calendar'),
        ),
    ]
