# Generated by Django 4.2.29 on 2026-04-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0006_calendarevent_lunardate_alter_holiday_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='name_kh',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name (Khmer)'),
        ),
    ]
