# Generated by Django 5.2.16 on 2026-07-31 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0009_pagevisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LunarDate',
        ),
    ]
