# Generated by Django 5.2.16 on 2026-08-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0010_remove_lunardate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tool',
            field=models.CharField(choices=[('compress', 'Compress'), ('merge', 'Merge'), ('split', 'Split'), ('protect', 'Protect')], default='compress', max_length=20),
        ),
    ]
