# Generated by Django 5.2.16 on 2026-08-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0011_add_protect_tool_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_google_vision', models.BooleanField(default=False, help_text='Off by default — OCR uses the built-in Tesseract engine (free). Turn this on once a service account key is pasted below.', verbose_name='Use Google Cloud Vision for OCR')),
                ('google_credentials_json', models.TextField(blank=True, help_text='Paste the full contents of the service account key file (the JSON you downloaded from Google Cloud Console → IAM & Admin → Service Accounts). Kept only in this row — treat it like a password.', verbose_name='Google Cloud service account JSON')),
                ('fallback_to_tesseract', models.BooleanField(default=True, help_text='Recommended. Keeps OCR working if the API key is invalid, the monthly quota is used up, or Google is unreachable.', verbose_name='Fall back to Tesseract if Google Vision fails')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OCR Settings',
                'verbose_name_plural': 'OCR Settings',
            },
        ),
    ]
